[package]
name = "nscope"
version = "0.1.0"
build = "build.rs"
authors = ["David Meyer <david@nscope.org>"]
edition = "2018"

[dependencies]
hidapi = "1.2.1"

[build-dependencies]
built = {version = "0.4.1", features= ["git2"]}