[package]
name = "nscope"
version = "1.0.0-dev"
authors = ["David Meyer <david@nscope.org>"]
license = "GPL-3.0"
description = """
Communication with nScope devices
"""
homepage = "https://www.nscope.org"
repository = "https://github.com/nLabs-nScope/nscope-rs"
documentation = "https://github.com/nLabs-nScope/nscope-rs"
readme = "README.md"
edition = "2018"

[dependencies]
hidapi = "1.2.1"
git-version = "0.3.4"
regex = "1"
enclose = "1.1.8"

[dev-dependencies]
semver = "0.9.0"