[package]
name = "nscope"
version = "0.1.0"
authors = ["David Meyer <david@nscope.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi = "1.2.1"
