name: Cargo Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  linux:
    name: on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get install libusb-1.0-0-dev
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run tests
        run: cargo test --verbose -- --nocapture

  macos:
    name: on Mac OS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run tests
        run: cargo test --verbose -- --nocapture

  windows:
    name: on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run tests
        run: cargo test --verbose -- --nocapture
